apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 750m
              memory: 512Mi