apiVersion: v1
kind: Service
metadata:
  name: transaction-ingestion
spec:
  selector:
    app: transaction-ingestion
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP