apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: transaction-platform

resources:
  - ../../base

images:
  - name: transaction-reporting-service
    newName: transaction-reporting-service
    newTag: local
  - name: transaction-frontend
    newName: transaction-frontend
    newTag: local

patches:
  - path: frontend-service-patch.yaml